spring.application.name=langchain4j-basics

ai.anthropic.api-key=${ANTHROPIC_API_KEY}
ai.anthropic.model-name=claude-sonnet-5-5
ai.anthropic.log-requests=true
ai.anthropic.log-responses=true

logging.level.dev.langchain4j=DEBUG
