spring.application.name=langchain4j-functions

langchain4j.anthropic.chat-model.api-key=${ANTHROPIC_API_KEY}
langchain4j.anthropic.chat-model.model-name=claude-sonnet-5-5
langchain4j.anthropic.chat-model.max-tokens=4096
langchain4j.anthropic.chat-model.log-requests=true
langchain4j.anthropic.chat-model.log-responses=true

logging.level.dev.langchain4j=DEBUG

api-ninjas.api-key=${API_NINJAS_API_KEY}
